name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd frontend
        npm install --force

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Deploy frontend
      run: scp -r frontend/dist/* root@47.97.175.75:/web/frontend
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd backend
        npm install

    - name: Build backend
      run: |
        cd backend
        npm run build

    - name: Deploy backend
      run: scp -r backend/dist/* root@47.97.175.75:/web/backend
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

